services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: pb138-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: pb138-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001 # (For local Docker testing. The user's browser needs to know where to send API requests. When you move to Rancher, change this to the public domain or IP of your backend ingress).
    ports:
      - "3000:80"
    depends_on:
      - backend