/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomNavRouteImport } from './routes/custom-nav'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayIndexRouteImport } from './routes/today/index'
import { Route as TimelineIndexRouteImport } from './routes/timeline/index'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OthersIndexRouteImport } from './routes/others/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeachersNewRouteImport } from './routes/teachers/new'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as CoursesNewRouteImport } from './routes/courses/new'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminDatabaseRouteImport } from './routes/admin/database'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomNavRoute = CustomNavRouteImport.update({
  id: '/custom-nav',
  path: '/custom-nav',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayIndexRoute = TodayIndexRouteImport.update({
  id: '/today/',
  path: '/today/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIndexRoute = TimelineIndexRouteImport.update({
  id: '/timeline/',
  path: '/timeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OthersIndexRoute = OthersIndexRouteImport.update({
  id: '/others/',
  path: '/others/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersNewRoute = TeachersNewRouteImport.update({
  id: '/teachers/new',
  path: '/teachers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesNewRoute = CoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDatabaseRoute = AdminDatabaseRouteImport.update({
  id: '/admin/database',
  path: '/admin/database',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-nav': typeof CustomNavRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/new': typeof CoursesNewRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/teachers/new': typeof TeachersNewRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/others/': typeof OthersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/timeline/': typeof TimelineIndexRoute
  '/today/': typeof TodayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-nav': typeof CustomNavRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/new': typeof CoursesNewRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/teachers/new': typeof TeachersNewRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/notes': typeof NotesIndexRoute
  '/others': typeof OthersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/timeline': typeof TimelineIndexRoute
  '/today': typeof TodayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-nav': typeof CustomNavRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/database': typeof AdminDatabaseRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/new': typeof CoursesNewRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/teachers/new': typeof TeachersNewRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/others/': typeof OthersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/timeline/': typeof TimelineIndexRoute
  '/today/': typeof TodayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-nav'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/database'
    | '/admin/logs'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/courses/$courseId'
    | '/courses/new'
    | '/notes/$noteId'
    | '/teachers/new'
    | '/admin/'
    | '/courses/'
    | '/notes/'
    | '/others/'
    | '/profile/'
    | '/tasks/'
    | '/teachers/'
    | '/timeline/'
    | '/today/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-nav'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/database'
    | '/admin/logs'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/courses/$courseId'
    | '/courses/new'
    | '/notes/$noteId'
    | '/teachers/new'
    | '/admin'
    | '/courses'
    | '/notes'
    | '/others'
    | '/profile'
    | '/tasks'
    | '/teachers'
    | '/timeline'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/custom-nav'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/database'
    | '/admin/logs'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/courses/$courseId'
    | '/courses/new'
    | '/notes/$noteId'
    | '/teachers/new'
    | '/admin/'
    | '/courses/'
    | '/notes/'
    | '/others/'
    | '/profile/'
    | '/tasks/'
    | '/teachers/'
    | '/timeline/'
    | '/today/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomNavRoute: typeof CustomNavRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminDatabaseRoute: typeof AdminDatabaseRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesNewRoute: typeof CoursesNewRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  TeachersNewRoute: typeof TeachersNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  OthersIndexRoute: typeof OthersIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  TimelineIndexRoute: typeof TimelineIndexRoute
  TodayIndexRoute: typeof TodayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-nav': {
      id: '/custom-nav'
      path: '/custom-nav'
      fullPath: '/custom-nav'
      preLoaderRoute: typeof CustomNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/': {
      id: '/today/'
      path: '/today'
      fullPath: '/today/'
      preLoaderRoute: typeof TodayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/': {
      id: '/timeline/'
      path: '/timeline'
      fullPath: '/timeline/'
      preLoaderRoute: typeof TimelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/others/': {
      id: '/others/'
      path: '/others'
      fullPath: '/others/'
      preLoaderRoute: typeof OthersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/new': {
      id: '/teachers/new'
      path: '/teachers/new'
      fullPath: '/teachers/new'
      preLoaderRoute: typeof TeachersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/new': {
      id: '/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof CoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/database': {
      id: '/admin/database'
      path: '/admin/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AdminDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomNavRoute: CustomNavRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminDatabaseRoute: AdminDatabaseRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesNewRoute: CoursesNewRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  TeachersNewRoute: TeachersNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  OthersIndexRoute: OthersIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  TimelineIndexRoute: TimelineIndexRoute,
  TodayIndexRoute: TodayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
